Plug 'ARivottiC/rivotti256.vim', { 'branch': 'develop' }
Plug 'Raimondi/delimitMate'
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'gerw/vim-HiLinkTrace'
Plug 'ntpeters/vim-better-whitespace'
Plug 'powerline/powerline'
Plug 'preservim/nerdtree'
Plug 'rubberduck203/aosp-vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/AutoComplPop'
Plug 'whatyouhide/vim-lengthmatters', { 'branch': 'main' }
